version: "3"
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass remixrocks
    expose:
      - "6379"
    volumes:
      - ./.cache/redis:/data
    ports:
      - "6379:6379"
  database:
    image: "postgres"
    restart: always
    volumes:
      - ./.cache/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=example_db
    ports:
      - "5432:5432"
